import { Metadata } from "next";
import React from "react";


export const metadata: Metadata = {
  title: "ProductList",
  description: "Generated by create next app",
};
export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {/* <h3>this is prodcuts related pages</h3> */}
      {children}
    </div>
  );
}
